"""Generate the frontend design tokens from ``netcast3r.theme``.

The terminal, the HTML report, and the dashboard must never disagree about a
colour, so both derived files are generated from the one Python source and
checked for drift in CI.

    python3 tools/gen_tokens.py            # write the files
    python3 tools/gen_tokens.py --check    # fail if they are stale
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from netcast3r import theme  # noqa: E402

CSS = ROOT / "web" / "src" / "tokens.css"
TS = ROOT / "web" / "src" / "tokens.ts"

HEADER = "/* Generated by tools/gen_tokens.py from src/netcast3r/theme.py. Do not edit. */\n"
TS_HEADER = "// Generated by tools/gen_tokens.py from src/netcast3r/theme.py. Do not edit.\n"

MOTION = {
    "ease-enter": "cubic-bezier(0.2, 0, 0, 1)",
    "ease-exit": "cubic-bezier(0.4, 0, 1, 1)",
    "t-hover": "120ms",
    "t-toggle": "180ms",
    "t-page": "240ms",
    "t-drawer": "300ms",
    "t-palette": "140ms",
}

SPACE = {str(i): f"{i * 4}px" for i in range(0, 25, 4)}
SCALE = {"xs": "12px", "sm": "13px", "base": "14px", "md": "16px", "lg": "20px",
         "xl": "25px", "2xl": "31px", "3xl": "39px"}


def _css() -> str:
    lines = [HEADER, "@theme {"]
    for name, value in theme.PALETTE.items():
        lines.append(f"  --color-{name.replace('_', '-')}: {value};")
    for name, value in theme.STATES.items():
        lines.append(f"  --color-state-{name.replace('_', '-')}: {value};")
    for name, value in theme.SEVERITIES.items():
        lines.append(f"  --color-sev-{name.replace('_', '-')}: {value};")
    for key, value in SCALE.items():
        lines.append(f"  --text-{key}: {value};")
    lines.append("}")

    lines += ["", ":root {", "  color-scheme: dark;"]
    for name, value in theme.PALETTE.items():
        lines.append(f"  --nc-{name}: {value};")
    for name, value in theme.STATES.items():
        lines.append(f"  --nc-state-{name}: {value};")
    for name, value in theme.SEVERITIES.items():
        lines.append(f"  --nc-sev-{name}: {value};")
    for name, value in MOTION.items():
        lines.append(f"  --{name}: {value};")
    for name, value in SPACE.items():
        lines.append(f"  --sp-{name}: {value};")
    lines.append("  --mono: ui-monospace, SFMono-Regular, Menlo, Consolas, \"Liberation Mono\", monospace;")
    lines.append("  --sans: system-ui, -apple-system, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif;")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _jsonish(data, indent: int = 2) -> str:
    if isinstance(data, dict):
        inner = ",\n".join(f"{' ' * (indent + 2)}{_jsonish(k)}: {_jsonish(v, indent + 2)}"
                           for k, v in data.items())
        return "{\n" + inner + "\n" + " " * indent + "}"
    if isinstance(data, list):
        inner = ",\n".join(f"{' ' * (indent + 2)}{_jsonish(v, indent + 2)}" for v in data)
        return "[\n" + inner + "\n" + " " * indent + "]"
    return json_string(str(data))


def json_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _ts() -> str:
    parts = [TS_HEADER,
             f"export const PALETTE = {_jsonish(theme.PALETTE)} as const;",
             f"export const STATES = {_jsonish(theme.STATES)} as const;",
             f"export const SEVERITIES = {_jsonish(theme.SEVERITIES)} as const;",
             f"export const STAGES = {_jsonish(theme.STAGES)} as const;",
             f"export const AGENT_STAGE = {_jsonish(theme.AGENT_STAGE)} as const;",
             f"export const AGENT_COLORS = {_jsonish(theme.AGENT_COLORS)} as const;",
             f"export const MARKS = {_jsonish({k: getattr(theme, k) for k in ('PROMPT', 'LIST_MARK', 'LIVE_MARK', 'CHEVRON')})} as const;",
             "export type Stage = (typeof STAGES)[number];",
             "export type Severity = keyof typeof SEVERITIES;",
             ""]
    return "\n".join(parts)


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for path, content in ((CSS, _css()), (TS, _ts())):
        if path.exists() and path.read_text() == content:
            continue
        stale.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    if check and stale:
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)}")
        print("run: python3 tools/gen_tokens.py")
        return 1
    if check:
        print("tokens up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
