// Generated by tools/gen_tokens.py from src/netcast3r/theme.py. Do not edit.

export const PALETTE = {
    "void": "#000000",
    "void_soft": "#010101",
    "acid": "#C8F81A",
    "acid_hot": "#F5F87D",
    "acid_dim": "#B1E61B",
    "acid_deep": "#6CA52E",
    "acid_abyss": "#172603",
    "violet": "#9F23DD",
    "violet_deep": "#4C2377",
    "violet_abyss": "#160334",
    "bone": "#F5E9DC",
    "bone_dim": "#FDF7E8",
    "indigo": "#281550",
    "indigo_deep": "#170F3F",
    "slate": "#2C2C4A",
    "gold": "#EFE4B1",
    "bone_dust": "#A89591",
    "ash": "#9698A2"
  } as const;
export const STATES = {
    "confirmed": "#C8F81A",
    "corroborated": "#EFE4B1",
    "inferred": "#9F23DD",
    "unresolved": "#2C2C4A",
    "rejected": "#4C2377",
    "live": "#C8F81A",
    "safe": "#9698A2",
    "unknown": "#2C2C4A"
  } as const;
export const SEVERITIES = {
    "critical": "#C8F81A",
    "high": "#F5F87D",
    "medium": "#EFE4B1",
    "low": "#A89591",
    "info": "#9698A2",
    "none": "#9698A2"
  } as const;
export const STAGES = [
    {
      "key": "crawl",
      "label": "CRAWL",
      "detail": "Target & Endpoints",
      "glyph": "@",
      "agent": "recon"
    },
    {
      "key": "readjs",
      "label": "READ JS",
      "detail": "Map Logic & Weak Spots",
      "glyph": "<>",
      "agent": "exegete"
    },
    {
      "key": "hunt",
      "label": "HUNT",
      "detail": "Secrets & Credentials",
      "glyph": "*",
      "agent": "prospector"
    },
    {
      "key": "validate",
      "label": "VALIDATE",
      "detail": "Check Access & Impact",
      "glyph": "^",
      "agent": "assayer"
    },
    {
      "key": "escalate",
      "label": "ESCALATE",
      "detail": "Find Highest Provable",
      "glyph": "^^",
      "agent": "chainer"
    },
    {
      "key": "report",
      "label": "REPORT",
      "detail": "Ready for Submission",
      "glyph": "#",
      "agent": "scribe"
    }
  ] as const;
export const AGENT_STAGE = {
    "recon": "crawl",
    "exegete": "readjs",
    "prospector": "hunt",
    "classifier": "hunt",
    "assayer": "validate",
    "chainer": "escalate",
    "scribe": "report",
    "sentinel": "validate",
    "run": "crawl"
  } as const;
export const AGENT_COLORS = {
    "recon": "#B1E61B",
    "exegete": "#9F23DD",
    "prospector": "#C8F81A",
    "classifier": "#F5F87D",
    "assayer": "#EFE4B1",
    "chainer": "#9F23DD",
    "scribe": "#F5E9DC",
    "sentinel": "#C8F81A",
    "run": "#A89591"
  } as const;
export const MARKS = {
    "PROMPT": ">_",
    "LIST_MARK": "//",
    "LIVE_MARK": "[*]",
    "CHEVRON": ">"
  } as const;
export type Stage = (typeof STAGES)[number];
export type Severity = keyof typeof SEVERITIES;
